version: '3'
services:
  postgres: 
    image: 'postgres:latest'
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgress_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules #leave this folder as it is
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 #redis does not allow port change
      - PGUSER=postgres
      - PGHOST=postgres #the name specified in docker-compose file
      - PGDATABASE=postgres
      - PGPASSWORD=postgress_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379